"use client";
import {useEffect,useMemo,useState} from "react";
import {createCashierSale,findCashierStudents,getCashierProducts} from "@/app/actions/sales";

type Student=Awaited<ReturnType<typeof findCashierStudents>>[number]; type Product=Awaited<ReturnType<typeof getCashierProducts>>[number];
export default function CashierClient(){
 const [q,setQ]=useState(""); const [results,setResults]=useState<Student[]>([]); const [student,setStudent]=useState<Student|null>(null); const [products,setProducts]=useState<Product[]>([]); const [cart,setCart]=useState<Record<string,number>>({}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [adminPassword,setAdminPassword]=useState(""); const [needsOverride,setNeedsOverride]=useState(false); const [key,setKey]=useState(()=>crypto.randomUUID());
 useEffect(()=>{getCashierProducts().then(setProducts)},[]);
 async function search(){setMessage("");const r=await findCashierStudents(q);setResults(r);if(r.length===1)select(r[0]);}
 function select(s:Student){setStudent(s);setResults([]);setQ(s.displayCode);setCart({});setMessage("");setNeedsOverride(false);}
 const total=useMemo(()=>products.reduce((n,p)=>n+Number(p.price)*(cart[p.id]||0),0),[products,cart]); const balance=student?.parent.wallet?Number(student.parent.wallet.balance):0;
 async function confirm(){if(!student||total<=0)return;setBusy(true);setMessage("");const items=Object.entries(cart).filter(([,quantity])=>quantity>0).map(([productId,quantity])=>({productId,quantity}));const r=await createCashierSale({studentId:student.id,items,idempotencyKey:key,adminPassword:adminPassword||undefined});setBusy(false);if(!r.ok){setNeedsOverride(Boolean(r.needsAdminOverride));setMessage(r.error||"Sale failed");return;}setMessage(`Sale ${r.saleNumber} completed. New balance: $${r.balanceAfter}`);setCart({});setAdminPassword("");setNeedsOverride(false);setKey(crypto.randomUUID());setTimeout(()=>{setStudent(null);setQ("");setMessage("")},1800);}
 return <main className="cashier"><div className="page-heading"><h1 className="brand">CanteenCo Cashier</h1><a className="secondary" href="/cashier/preorders">Pre-Orders</a></div><div className="panel"><label className="label">Scan QR, enter student code, or search name<div style={{display:"flex",gap:8}}><input className="input" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="3C-001"/><button className="primary" onClick={search}>Search</button></div></label>{results.length>1&&<div>{results.map(s=><button key={s.id} className="product" onClick={()=>select(s)}>{s.firstName} {s.lastName} — {s.displayCode}</button>)}</div>}</div>
 {student&&<><div className="panel"><strong>{student.firstName} {student.lastName}</strong> · {student.displayCode} · Class {student.classCode}<br/><span className="subtle">Family wallet</span> <strong>${balance.toFixed(2)}</strong>{balance<=0&&<p><strong>Insufficient/negative balance — admin approval will be required if school policy allows.</strong></p>}</div><section className="cashier-grid"><div className="panel"><h2>Products</h2><div className="products">{products.map(p=><button className="product" key={p.id} onClick={()=>setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}))}><strong>{p.name}</strong><br/>${Number(p.price).toFixed(2)}{cart[p.id]?` × ${cart[p.id]}`:""}</button>)}</div></div><aside className="panel"><h2>Current Sale</h2>{products.filter(p=>cart[p.id]).map(p=><div key={p.id}>{p.name} × {cart[p.id]} <button onClick={()=>setCart(c=>({...c,[p.id]:Math.max(0,(c[p.id]||0)-1)}))}>−</button></div>)}<div className="divider"/><strong>Total: ${total.toFixed(2)}</strong><br/><span>Projected balance: ${(balance-total).toFixed(2)}</span>{needsOverride&&<label className="label">Admin password<input className="input" type="password" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)}/></label>}<div style={{height:12}}/><button disabled={busy||total<=0} className="primary" style={{width:"100%"}} onClick={confirm}>{busy?"Processing…":needsOverride?"Approve & Complete Sale":"Confirm Sale"}</button>{message&&<p>{message}</p>}</aside></section></>}
 </main>;
}
